name: Solar System Workflow

on:
    workflow_dispatch:
    push:
      branches:
        - main
        - 'feature/*'
env:
    MONGO_URI: 'mongosh docdb-2025-03-01-07-23-33.cluster-cehi0w0w8fu7.us-east-1.docdb.amazonaws.com:27017 --tls --tlsCAFile global-bundle.pem'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  unit-testing:
    name: Unit-Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS version - 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependecies
      run: npm install

    - name: Unit Testing
      run: npm test